name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Setup MacOs 12
    runs-on: macos-12

    steps:

      - name: XCode setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Bundle install
        run: bundle install
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install lizard
        run: pip install lizard
        
      - name: Install Sonar scanner
        run: brew install sonar-scanner

      - name: Install Swiftgen
        run: sudo ln -s /opt/homebrew/bin/swiftgen /usr/local/bin/swiftgen

      - name: Build and test
        run: |
          bundle exec fastlane test \
          sonar_login:"$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}